# Generated by Django 3.0.4 on 2020-03-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('position', models.TextField()),
                ('detailed_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
