# Generated by Django 3.0.4 on 2020-03-30 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_skillitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateitem',
            name='picture',
        ),
        migrations.CreateModel(
            name='PrivatePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('private_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.PrivateItem')),
            ],
        ),
    ]
